[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "1.15.36"

[[constraint]]
  name = "github.com/blang/semver"
  version = "3.5.1"

[[constraint]]
  name = "github.com/mitchellh/go-homedir"
  version = "1.0.0"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.0.6"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.3"

[[constraint]]
  branch = "master"
  name = "golang.org/x/crypto"

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  branch = "edu/go-misc-aws"
  name = "github.com/chanzuckerberg/go-kmsauth"

[[constraint]]
  branch = "edu/initial"
  name = "github.com/chanzuckerberg/go-misc"

[[constraint]]
  name = "github.com/segmentio/go-prompt"
  branch = "master"

[[constraint]]
  branch = "master"
  name = "github.com/hashicorp/go-getter"
