[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "1.16.5"

[[constraint]]
  name = "github.com/blang/semver"
  version = "3.5.1"

[[constraint]]
  name = "github.com/cenkalti/backoff"
  version = "2.1.0"

[[constraint]]
  branch = "master"
  name = "github.com/chanzuckerberg/go-misc"

[[constraint]]
  name = "github.com/davecgh/go-spew"
  version = "1.1.1"

[[constraint]]
  name = "github.com/google/uuid"
  version = "1.1.0"

[[constraint]]
  branch = "master"
  name = "github.com/hashicorp/go-getter"

[[constraint]]
  name = "github.com/hashicorp/go-multierror"
  version = "1.0.0"

[[constraint]]
  branch = "master"
  name = "github.com/honeycombio/opencensus-exporter"

[[constraint]]
  name = "github.com/mitchellh/go-homedir"
  version = "1.0.0"

[[constraint]]
  branch = "master"
  name = "github.com/nightlyone/lockfile"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"

[[constraint]]
  branch = "master"
  name = "github.com/segmentio/aws-okta"
  source = "github.com/chanzuckerberg/aws-okta"

[[constraint]]
  name = "github.com/segmentio/go-prompt"
  branch = "master"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.2.0"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.3"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.2"

[[constraint]]
  name = "go.opencensus.io"
  version = "0.18.0"

[[constraint]]
  branch = "master"
  name = "golang.org/x/crypto"

[[constraint]]
  name = "gopkg.in/yaml.v2"
  version = "2.2.2"

[prune]
  go-tests = true
  unused-packages = true
